/* Generated by Yosys 0.58+86 (git sha1 3b9f06c13, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

(* src = "mac_pe.v:3.1-23.10" *)
module pe(clk, rst, a_in, b_in, a_out, b_out, c);
  (* src = "mac_pe.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "mac_pe.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "mac_pe.v:6.17-6.21" *)
  input [7:0] a_in;
  wire [7:0] a_in;
  (* src = "mac_pe.v:7.17-7.21" *)
  input [7:0] b_in;
  wire [7:0] b_in;
  (* src = "mac_pe.v:8.22-8.27" *)
  output [7:0] a_out;
  reg [7:0] a_out;
  (* src = "mac_pe.v:9.22-9.27" *)
  output [7:0] b_out;
  reg [7:0] b_out;
  (* src = "mac_pe.v:10.23-10.24" *)
  output [15:0] c;
  reg [15:0] c;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.20-198.21" *)
  wire [15:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.20-198.21" *)
  wire [15:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [15:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [15:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [15:0] _043_;
  (* force_downto = 32'd1 *)
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [15:0] _044_;
  (* force_downto = 32'd1 *)
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  (* unused_bits = "15" *)
  wire [15:0] _045_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _046_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _047_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _048_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _049_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _050_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _051_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _052_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _053_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _054_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _055_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _056_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _057_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _058_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _059_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _060_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _061_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _062_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _063_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _064_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _065_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _066_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _067_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _068_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _069_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _070_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _071_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _072_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _073_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _074_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _075_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _076_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _077_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _078_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _079_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _080_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _081_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _082_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _083_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _084_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _085_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _086_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _087_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _088_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _089_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _090_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _091_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _092_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _093_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _094_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _095_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _096_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _097_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _098_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _099_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _100_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _101_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _102_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _103_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _104_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _105_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _106_;
  (* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _107_;
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[8] <= 1'h0;
    else c[8] <= _044_[8];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[9] <= 1'h0;
    else c[9] <= _044_[9];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[10] <= 1'h0;
    else c[10] <= _044_[10];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[11] <= 1'h0;
    else c[11] <= _044_[11];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[12] <= 1'h0;
    else c[12] <= _044_[12];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[13] <= 1'h0;
    else c[13] <= _044_[13];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[14] <= 1'h0;
    else c[14] <= _044_[14];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[15] <= 1'h0;
    else c[15] <= _044_[15];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[0] <= 1'h0;
    else a_out[0] <= a_in[0];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[1] <= 1'h0;
    else a_out[1] <= a_in[1];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[2] <= 1'h0;
    else a_out[2] <= a_in[2];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[3] <= 1'h0;
    else a_out[3] <= a_in[3];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[4] <= 1'h0;
    else a_out[4] <= a_in[4];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[5] <= 1'h0;
    else a_out[5] <= a_in[5];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[6] <= 1'h0;
    else a_out[6] <= a_in[6];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) a_out[7] <= 1'h0;
    else a_out[7] <= a_in[7];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[0] <= 1'h0;
    else b_out[0] <= b_in[0];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[1] <= 1'h0;
    else b_out[1] <= b_in[1];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[2] <= 1'h0;
    else b_out[2] <= b_in[2];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[3] <= 1'h0;
    else b_out[3] <= b_in[3];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[4] <= 1'h0;
    else b_out[4] <= b_in[4];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[5] <= 1'h0;
    else b_out[5] <= b_in[5];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[6] <= 1'h0;
    else b_out[6] <= b_in[6];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) b_out[7] <= 1'h0;
    else b_out[7] <= b_in[7];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[0] <= 1'h0;
    else c[0] <= _043_[0];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[1] <= 1'h0;
    else c[1] <= _044_[1];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[2] <= 1'h0;
    else c[2] <= _044_[2];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[3] <= 1'h0;
    else c[3] <= _044_[3];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[4] <= 1'h0;
    else c[4] <= _044_[4];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[5] <= 1'h0;
    else c[5] <= _044_[5];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[6] <= 1'h0;
    else c[6] <= _044_[6];
  (* src = "mac_pe.v:12.5-22.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[7] <= 1'h0;
    else c[7] <= _044_[7];
  assign _042_[0] = c[0] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _000_[0];
  assign _045_[1] = c[1] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _004_[1];
  assign _045_[2] = c[2] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _017_[2];
  assign _045_[3] = c[3] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _029_[3];
  assign _045_[4] = c[4] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _034_[4];
  assign _045_[5] = c[5] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _039_[5];
  assign _045_[6] = c[6] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[6];
  assign _045_[7] = c[7] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[7];
  assign _045_[8] = c[8] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[8];
  assign _045_[9] = c[9] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[9];
  assign _045_[10] = c[10] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[10];
  assign _045_[11] = c[11] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[11];
  assign _045_[12] = c[12] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[12];
  assign _045_[13] = c[13] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[13];
  assign _045_[14] = c[14] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _040_[14];
  assign _043_[0] = c[0] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _000_[0];
  assign _043_[1] = c[1] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _004_[1];
  assign _043_[2] = c[2] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _017_[2];
  assign _043_[3] = c[3] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _029_[3];
  assign _043_[4] = c[4] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _034_[4];
  assign _043_[5] = c[5] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _039_[5];
  assign _043_[6] = c[6] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[6];
  assign _043_[7] = c[7] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[7];
  assign _043_[8] = c[8] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[8];
  assign _043_[9] = c[9] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[9];
  assign _043_[10] = c[10] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[10];
  assign _043_[11] = c[11] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[11];
  assign _043_[12] = c[12] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[12];
  assign _043_[13] = c[13] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[13];
  assign _043_[14] = c[14] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[14];
  assign _043_[15] = c[15] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _040_[15];
  assign _070_ = _043_[1] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _042_[0];
  assign _071_ = _043_[3] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[2];
  assign _072_ = _043_[5] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[4];
  assign _073_ = _043_[7] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[6];
  assign _074_ = _043_[9] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[8];
  assign _075_ = _043_[11] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[10];
  assign _076_ = _043_[13] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[12];
  assign _077_ = _081_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _042_[1];
  assign _078_ = _083_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _101_;
  assign _079_ = _085_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _103_;
  assign _080_ = _087_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _042_[3];
  assign _081_ = _043_[3] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[2];
  assign _082_ = _043_[5] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[4];
  assign _083_ = _043_[7] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[6];
  assign _084_ = _043_[9] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[8];
  assign _085_ = _043_[11] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[10];
  assign _086_ = _043_[13] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[12];
  assign _087_ = _083_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _082_;
  assign _088_ = _085_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _084_;
  assign _089_ = _088_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[7];
  assign _090_ = _082_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[3];
  assign _091_ = _084_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[7];
  assign _092_ = _086_ &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[11];
  assign _093_ = _043_[2] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[1];
  assign _094_ = _043_[4] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[3];
  assign _095_ = _043_[6] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[5];
  assign _096_ = _043_[8] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[7];
  assign _097_ = _043_[10] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[9];
  assign _098_ = _043_[12] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[11];
  assign _099_ = _043_[14] &(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[13];
  assign _042_[1] = _045_[1] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _070_;
  assign _100_ = _045_[3] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _071_;
  assign _101_ = _045_[5] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _072_;
  assign _102_ = _045_[7] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _073_;
  assign _103_ = _045_[9] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _074_;
  assign _104_ = _045_[11] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _075_;
  assign _105_ = _045_[13] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _076_;
  assign _042_[3] = _100_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _077_;
  assign _106_ = _102_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _078_;
  assign _107_ = _104_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _079_;
  assign _042_[7] = _106_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _080_;
  assign _042_[11] = _107_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _089_;
  assign _042_[5] = _101_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _090_;
  assign _042_[9] = _103_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _091_;
  assign _042_[13] = _105_ |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _092_;
  assign _042_[2] = _045_[2] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _093_;
  assign _042_[4] = _045_[4] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _094_;
  assign _042_[6] = _045_[6] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _095_;
  assign _042_[8] = _045_[8] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _096_;
  assign _042_[10] = _045_[10] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _097_;
  assign _042_[12] = _045_[12] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _098_;
  assign _042_[14] = _045_[14] |(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _099_;
  assign _038_[5] = _034_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[4];
  assign _041_[6] = _034_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[5];
  assign _041_[7] = _034_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[6];
  assign _041_[8] = _034_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[7];
  assign _041_[9] = _034_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[8];
  assign _041_[10] = _034_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[9];
  assign _041_[11] = _034_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[10];
  assign _041_[12] = _034_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[11];
  assign _041_[13] = _034_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[12];
  assign _041_[14] = _034_[14] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[13];
  assign _039_[5] = _034_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[4];
  assign _039_[6] = _034_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[5];
  assign _039_[7] = _034_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[6];
  assign _039_[8] = _034_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[7];
  assign _039_[9] = _034_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[8];
  assign _039_[10] = _034_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[9];
  assign _039_[11] = _034_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[10];
  assign _039_[12] = _034_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[11];
  assign _039_[13] = _034_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[12];
  assign _039_[14] = _034_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[13];
  assign _046_ = _039_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[6];
  assign _047_ = _039_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[8];
  assign _048_ = _039_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[10];
  assign _049_ = _039_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[12];
  assign _050_ = _052_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _038_[5];
  assign _051_ = _054_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _066_;
  assign _052_ = _039_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[6];
  assign _053_ = _039_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[8];
  assign _054_ = _039_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[10];
  assign _055_ = _039_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[12];
  assign _056_ = _054_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _053_;
  assign _057_ = _056_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _058_ = _053_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _059_ = _055_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _060_ = _039_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[5];
  assign _061_ = _039_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _062_ = _039_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[9];
  assign _063_ = _039_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _064_ = _039_[14] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[13];
  assign _065_ = _041_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _046_;
  assign _066_ = _041_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _047_;
  assign _067_ = _041_[11] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _048_;
  assign _068_ = _041_[13] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _049_;
  assign _038_[7] = _065_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _050_;
  assign _069_ = _067_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _051_;
  assign _038_[11] = _069_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _057_;
  assign _038_[9] = _066_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _058_;
  assign _038_[13] = _068_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _059_;
  assign _038_[6] = _041_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _060_;
  assign _038_[8] = _041_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _061_;
  assign _038_[10] = _041_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _062_;
  assign _038_[12] = _041_[12] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _063_;
  assign _038_[14] = _041_[14] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _064_;
  assign _000_[0] = a_in[0] & b_in[0];
  assign _000_[1] = a_in[1] & b_in[0];
  assign _000_[2] = a_in[2] & b_in[0];
  assign _000_[3] = a_in[3] & b_in[0];
  assign _000_[4] = a_in[4] & b_in[0];
  assign _000_[5] = a_in[5] & b_in[0];
  assign _000_[6] = a_in[6] & b_in[0];
  assign _000_[7] = a_in[7] & b_in[0];
  assign _001_[1] = a_in[0] & b_in[1];
  assign _001_[2] = a_in[1] & b_in[1];
  assign _001_[3] = a_in[2] & b_in[1];
  assign _001_[4] = a_in[3] & b_in[1];
  assign _001_[5] = a_in[4] & b_in[1];
  assign _001_[6] = a_in[5] & b_in[1];
  assign _001_[7] = a_in[6] & b_in[1];
  assign _001_[8] = a_in[7] & b_in[1];
  assign _002_[2] = a_in[0] & b_in[2];
  assign _002_[3] = a_in[1] & b_in[2];
  assign _002_[4] = a_in[2] & b_in[2];
  assign _002_[5] = a_in[3] & b_in[2];
  assign _002_[6] = a_in[4] & b_in[2];
  assign _002_[7] = a_in[5] & b_in[2];
  assign _002_[8] = a_in[6] & b_in[2];
  assign _002_[9] = a_in[7] & b_in[2];
  assign _008_[3] = a_in[0] & b_in[3];
  assign _008_[4] = a_in[1] & b_in[3];
  assign _008_[5] = a_in[2] & b_in[3];
  assign _008_[6] = a_in[3] & b_in[3];
  assign _008_[7] = a_in[4] & b_in[3];
  assign _008_[8] = a_in[5] & b_in[3];
  assign _008_[9] = a_in[6] & b_in[3];
  assign _008_[10] = a_in[7] & b_in[3];
  assign _009_[4] = a_in[0] & b_in[4];
  assign _009_[5] = a_in[1] & b_in[4];
  assign _009_[6] = a_in[2] & b_in[4];
  assign _009_[7] = a_in[3] & b_in[4];
  assign _009_[8] = a_in[4] & b_in[4];
  assign _009_[9] = a_in[5] & b_in[4];
  assign _009_[10] = a_in[6] & b_in[4];
  assign _009_[11] = a_in[7] & b_in[4];
  assign _010_[5] = a_in[0] & b_in[5];
  assign _010_[6] = a_in[1] & b_in[5];
  assign _010_[7] = a_in[2] & b_in[5];
  assign _010_[8] = a_in[3] & b_in[5];
  assign _010_[9] = a_in[4] & b_in[5];
  assign _010_[10] = a_in[5] & b_in[5];
  assign _010_[11] = a_in[6] & b_in[5];
  assign _010_[12] = a_in[7] & b_in[5];
  assign _021_[6] = a_in[0] & b_in[6];
  assign _021_[7] = a_in[1] & b_in[6];
  assign _021_[8] = a_in[2] & b_in[6];
  assign _021_[9] = a_in[3] & b_in[6];
  assign _021_[10] = a_in[4] & b_in[6];
  assign _021_[11] = a_in[5] & b_in[6];
  assign _021_[12] = a_in[6] & b_in[6];
  assign _021_[13] = a_in[7] & b_in[6];
  assign _022_[7] = a_in[0] & b_in[7];
  assign _022_[8] = a_in[1] & b_in[7];
  assign _022_[9] = a_in[2] & b_in[7];
  assign _022_[10] = a_in[3] & b_in[7];
  assign _022_[11] = a_in[4] & b_in[7];
  assign _022_[12] = a_in[5] & b_in[7];
  assign _022_[13] = a_in[6] & b_in[7];
  assign _022_[14] = a_in[7] & b_in[7];
  assign _044_[1] = _043_[1] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[0];
  assign _044_[2] = _043_[2] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[1];
  assign _044_[3] = _043_[3] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[2];
  assign _044_[4] = _043_[4] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[3];
  assign _044_[5] = _043_[5] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[4];
  assign _044_[6] = _043_[6] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[5];
  assign _044_[7] = _043_[7] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[6];
  assign _044_[8] = _043_[8] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[7];
  assign _044_[9] = _043_[9] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[8];
  assign _044_[10] = _043_[10] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[9];
  assign _044_[11] = _043_[11] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[10];
  assign _044_[12] = _043_[12] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[11];
  assign _044_[13] = _043_[13] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[12];
  assign _044_[14] = _043_[14] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[13];
  assign _044_[15] = _043_[15] ^(* src = "mac_pe.v:20.18-20.35|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[14];
  assign _003_[2] = _006_[2] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[2];
  assign _003_[3] = _006_[3] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[3];
  assign _003_[4] = _006_[4] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[4];
  assign _003_[5] = _006_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[5];
  assign _003_[6] = _006_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[6];
  assign _003_[7] = _006_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[7];
  assign _004_[2] = _005_[2] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[2];
  assign _004_[3] = _005_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[3];
  assign _004_[4] = _005_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[4];
  assign _004_[5] = _005_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[5];
  assign _004_[6] = _005_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[6];
  assign _004_[7] = _005_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[7];
  assign _004_[8] = _001_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[8];
  assign _007_[2] = _002_[2] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[2];
  assign _007_[3] = _002_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[3];
  assign _007_[4] = _002_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[4];
  assign _007_[5] = _002_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[5];
  assign _007_[6] = _002_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[6];
  assign _007_[7] = _002_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[7];
  assign _003_[8] = _002_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _001_[8];
  assign _003_[1] = _000_[1] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[1];
  assign _006_[2] = _000_[2] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[2];
  assign _006_[3] = _000_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[3];
  assign _006_[4] = _000_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[4];
  assign _006_[5] = _000_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[5];
  assign _006_[6] = _000_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[6];
  assign _006_[7] = _000_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[7];
  assign _004_[1] = _000_[1] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[1];
  assign _005_[2] = _000_[2] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[2];
  assign _005_[3] = _000_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[3];
  assign _005_[4] = _000_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[4];
  assign _005_[5] = _000_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[5];
  assign _005_[6] = _000_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[6];
  assign _005_[7] = _000_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[7];
  assign _011_[5] = _014_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[5];
  assign _011_[6] = _014_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[6];
  assign _011_[7] = _014_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[7];
  assign _011_[8] = _014_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[8];
  assign _011_[9] = _014_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[9];
  assign _011_[10] = _014_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[10];
  assign _012_[5] = _013_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[5];
  assign _012_[6] = _013_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[6];
  assign _012_[7] = _013_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[7];
  assign _012_[8] = _013_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[8];
  assign _012_[9] = _013_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[9];
  assign _012_[10] = _013_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[10];
  assign _012_[11] = _009_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[11];
  assign _015_[5] = _010_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[5];
  assign _015_[6] = _010_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[6];
  assign _015_[7] = _010_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[7];
  assign _015_[8] = _010_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[8];
  assign _015_[9] = _010_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[9];
  assign _015_[10] = _010_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[10];
  assign _011_[11] = _010_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _009_[11];
  assign _011_[4] = _008_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[4];
  assign _014_[5] = _008_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[5];
  assign _014_[6] = _008_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[6];
  assign _014_[7] = _008_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[7];
  assign _014_[8] = _008_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[8];
  assign _014_[9] = _008_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[9];
  assign _014_[10] = _008_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[10];
  assign _012_[4] = _008_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[4];
  assign _013_[5] = _008_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[5];
  assign _013_[6] = _008_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[6];
  assign _013_[7] = _008_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[7];
  assign _013_[8] = _008_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[8];
  assign _013_[9] = _008_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[9];
  assign _013_[10] = _008_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[10];
  assign _016_[3] = _019_[3] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[3];
  assign _016_[4] = _019_[4] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[4];
  assign _016_[5] = _019_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[5];
  assign _016_[6] = _019_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[6];
  assign _016_[7] = _019_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[7];
  assign _016_[8] = _019_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[8];
  assign _016_[9] = _019_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[9];
  assign _017_[3] = _018_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _008_[3];
  assign _017_[4] = _018_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[4];
  assign _017_[5] = _018_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[5];
  assign _017_[6] = _018_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[6];
  assign _017_[7] = _018_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[7];
  assign _017_[8] = _018_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[8];
  assign _017_[9] = _018_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[9];
  assign _020_[3] = _008_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[3];
  assign _020_[4] = _012_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[4];
  assign _020_[5] = _012_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[5];
  assign _020_[6] = _012_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[6];
  assign _020_[7] = _012_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[7];
  assign _020_[8] = _012_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[8];
  assign _020_[9] = _012_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[9];
  assign _016_[2] = _004_[2] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[1];
  assign _019_[3] = _004_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[2];
  assign _019_[4] = _004_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[3];
  assign _019_[5] = _004_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[4];
  assign _019_[6] = _004_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[5];
  assign _019_[7] = _004_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[6];
  assign _019_[8] = _004_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[7];
  assign _019_[9] = _002_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[8];
  assign _017_[2] = _004_[2] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[1];
  assign _018_[3] = _004_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[2];
  assign _018_[4] = _004_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[3];
  assign _018_[5] = _004_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[4];
  assign _018_[6] = _004_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[5];
  assign _018_[7] = _004_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[6];
  assign _018_[8] = _004_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[7];
  assign _018_[9] = _002_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[8];
  assign _023_[7] = _026_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[7];
  assign _023_[8] = _026_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[8];
  assign _023_[9] = _026_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[9];
  assign _023_[10] = _026_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[10];
  assign _023_[11] = _026_[11] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[11];
  assign _023_[12] = _026_[12] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[12];
  assign _024_[7] = _025_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[7];
  assign _024_[8] = _025_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[8];
  assign _024_[9] = _025_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[9];
  assign _024_[10] = _025_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[10];
  assign _024_[11] = _025_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[11];
  assign _024_[12] = _025_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[12];
  assign _024_[13] = _021_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[13];
  assign _027_[7] = _022_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[7];
  assign _027_[8] = _022_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[8];
  assign _027_[9] = _022_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[9];
  assign _027_[10] = _022_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[10];
  assign _027_[11] = _022_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[11];
  assign _027_[12] = _022_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[12];
  assign _023_[13] = _022_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _021_[13];
  assign _023_[6] = _011_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[6];
  assign _026_[7] = _011_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[7];
  assign _026_[8] = _011_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[8];
  assign _026_[9] = _011_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[9];
  assign _026_[10] = _011_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[10];
  assign _026_[11] = _011_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[11];
  assign _026_[12] = _011_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[12];
  assign _024_[6] = _011_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[6];
  assign _025_[7] = _011_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[7];
  assign _025_[8] = _011_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[8];
  assign _025_[9] = _011_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[9];
  assign _025_[10] = _011_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[10];
  assign _025_[11] = _011_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[11];
  assign _025_[12] = _011_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[12];
  assign _028_[5] = _031_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[5];
  assign _028_[6] = _031_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[6];
  assign _028_[7] = _031_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[7];
  assign _028_[8] = _031_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[8];
  assign _028_[9] = _031_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[9];
  assign _028_[10] = _031_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[10];
  assign _029_[5] = _030_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _011_[4];
  assign _029_[6] = _030_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[6];
  assign _029_[7] = _030_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[7];
  assign _029_[8] = _030_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[8];
  assign _029_[9] = _030_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[9];
  assign _029_[10] = _030_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[10];
  assign _029_[11] = _012_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[11];
  assign _029_[12] = _010_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[12];
  assign _032_[5] = _011_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[5];
  assign _032_[6] = _024_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[6];
  assign _032_[7] = _024_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[7];
  assign _032_[8] = _024_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[8];
  assign _032_[9] = _024_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[9];
  assign _032_[10] = _024_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[10];
  assign _028_[11] = _024_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _012_[11];
  assign _028_[12] = _024_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _010_[12];
  assign _028_[3] = _017_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[2];
  assign _028_[4] = _017_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[3];
  assign _031_[5] = _017_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[4];
  assign _031_[6] = _017_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[5];
  assign _031_[7] = _017_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[6];
  assign _031_[8] = _017_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[7];
  assign _031_[9] = _017_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[8];
  assign _031_[10] = _012_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[9];
  assign _029_[3] = _017_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[2];
  assign _029_[4] = _017_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[3];
  assign _030_[5] = _017_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[4];
  assign _030_[6] = _017_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[5];
  assign _030_[7] = _017_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[6];
  assign _030_[8] = _017_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[7];
  assign _030_[9] = _017_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[8];
  assign _030_[10] = _012_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[9];
  assign _033_[7] = _036_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[7];
  assign _033_[8] = _036_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[8];
  assign _033_[9] = _036_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[9];
  assign _033_[10] = _036_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[10];
  assign _033_[11] = _036_[11] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[11];
  assign _033_[12] = _036_[12] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[12];
  assign _033_[13] = _036_[13] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[13];
  assign _034_[7] = _035_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[6];
  assign _034_[8] = _035_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[7];
  assign _034_[9] = _035_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[8];
  assign _034_[10] = _035_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[9];
  assign _034_[11] = _035_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[10];
  assign _034_[12] = _035_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[11];
  assign _034_[13] = _035_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[12];
  assign _034_[14] = _022_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[13];
  assign _037_[7] = _023_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[7];
  assign _037_[8] = _023_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[8];
  assign _037_[9] = _023_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[9];
  assign _037_[10] = _023_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[10];
  assign _037_[11] = _023_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[11];
  assign _037_[12] = _023_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[12];
  assign _037_[13] = _023_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[13];
  assign _033_[14] = _023_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _022_[14];
  assign _033_[4] = _029_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[3];
  assign _033_[5] = _029_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[4];
  assign _033_[6] = _029_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[5];
  assign _036_[7] = _029_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[6];
  assign _036_[8] = _029_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[7];
  assign _036_[9] = _029_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[8];
  assign _036_[10] = _029_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[9];
  assign _036_[11] = _029_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[10];
  assign _036_[12] = _029_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[11];
  assign _036_[13] = _024_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[12];
  assign _034_[4] = _029_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[3];
  assign _034_[5] = _029_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[4];
  assign _034_[6] = _029_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[5];
  assign _035_[7] = _029_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[6];
  assign _035_[8] = _029_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[7];
  assign _035_[9] = _029_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[8];
  assign _035_[10] = _029_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[9];
  assign _035_[11] = _029_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[10];
  assign _035_[12] = _029_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[11];
  assign _035_[13] = _024_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[12];
  assign _040_[6] = _039_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[5];
  assign _040_[7] = _039_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[6];
  assign _040_[8] = _039_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[7];
  assign _040_[9] = _039_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[8];
  assign _040_[10] = _039_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[9];
  assign _040_[11] = _039_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[10];
  assign _040_[12] = _039_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[11];
  assign _040_[13] = _039_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[12];
  assign _040_[14] = _039_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[13];
  assign _040_[15] = _033_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[14];
  assign _000_[15:8] = 8'h00;
  assign { _001_[15:9], _001_[0] } = 8'h00;
  assign { _002_[15:10], _002_[1:0] } = 8'h00;
  assign { _003_[15:9], _003_[0] } = 8'h00;
  assign { _004_[15:9], _004_[0] } = { 6'h00, _002_[9], _000_[0] };
  assign { _005_[15:8], _005_[1:0] } = { 7'h00, _001_[8], _004_[1], _000_[0] };
  assign { _006_[15:8], _006_[1:0] } = { 8'h00, _003_[1], 1'h0 };
  assign { _007_[15:8], _007_[1:0] } = { 7'h00, _003_[8], 2'h0 };
  assign { _008_[15:11], _008_[2:0] } = 8'h00;
  assign { _009_[15:12], _009_[3:0] } = 8'h00;
  assign { _010_[15:13], _010_[4:0] } = 8'h00;
  assign { _011_[15:12], _011_[3:0] } = 8'h00;
  assign { _012_[15:12], _012_[3:0] } = { 3'h0, _010_[12], _008_[3], 3'h0 };
  assign { _013_[15:11], _013_[4:0] } = { 4'h0, _009_[11], _012_[4], _008_[3], 3'h0 };
  assign { _014_[15:11], _014_[4:0] } = { 5'h00, _011_[4], 4'h0 };
  assign { _015_[15:11], _015_[4:0] } = { 4'h0, _011_[11], 5'h00 };
  assign { _016_[15:10], _016_[1:0] } = 8'h00;
  assign { _017_[15:10], _017_[1:0] } = { 3'h0, _010_[12], _012_[11:10], _004_[1], _000_[0] };
  assign { _018_[15:10], _018_[2:0] } = { 6'h00, _017_[2], _004_[1], _000_[0] };
  assign { _019_[15:10], _019_[2:0] } = { 6'h00, _016_[2], 2'h0 };
  assign { _020_[15:10], _020_[2:0] } = 9'h000;
  assign { _021_[15:14], _021_[5:0] } = 8'h00;
  assign { _022_[15], _022_[6:0] } = 8'h00;
  assign { _023_[15:14], _023_[5:0] } = 8'h00;
  assign { _024_[15:14], _024_[5:0] } = { 1'h0, _022_[14], _011_[4], 5'h00 };
  assign { _025_[15:13], _025_[6:0] } = { 2'h0, _021_[13], _024_[6], _011_[4], 5'h00 };
  assign { _026_[15:13], _026_[6:0] } = { 3'h0, _023_[6], 6'h00 };
  assign { _027_[15:13], _027_[6:0] } = { 2'h0, _023_[13], 7'h00 };
  assign { _028_[15:13], _028_[2:0] } = 6'h00;
  assign { _029_[15:13], _029_[2:0] } = { 1'h0, _022_[14], _024_[13], _017_[2], _004_[1], _000_[0] };
  assign { _030_[15:11], _030_[4:0] } = { 3'h0, _010_[12], _012_[11], _029_[4:3], _017_[2], _004_[1], _000_[0] };
  assign { _031_[15:11], _031_[4:0] } = { 5'h00, _028_[4:3], 3'h0 };
  assign { _032_[15:11], _032_[4:0] } = { 3'h0, _028_[12:11], 5'h00 };
  assign { _033_[15], _033_[3:0] } = 5'h00;
  assign { _034_[15], _034_[3:0] } = { 1'h0, _029_[3], _017_[2], _004_[1], _000_[0] };
  assign { _035_[15:14], _035_[6:0] } = { 1'h0, _022_[14], _034_[6:4], _029_[3], _017_[2], _004_[1], _000_[0] };
  assign { _036_[15:14], _036_[6:0] } = { 2'h0, _033_[6:4], 4'h0 };
  assign { _037_[15:14], _037_[6:0] } = { 1'h0, _033_[14], 7'h00 };
  assign _038_[4:0] = 5'h00;
  assign { _039_[15], _039_[4:0] } = { _033_[14], _034_[4], _029_[3], _017_[2], _004_[1], _000_[0] };
  assign _040_[5:0] = { _039_[5], _034_[4], _029_[3], _017_[2], _004_[1], _000_[0] };
  assign { _041_[15], _041_[5:0] } = { 1'h0, _038_[5], 5'h00 };
  assign _044_[0] = _043_[0];
  assign _045_[0] = _042_[0];
endmodule

(* top =  1  *)
(* src = "systolic_array.v:3.1-46.10" *)
module systolic_array(clk, rst, a1, a2, b1, b2, c11, c12, c21, c22);
  (* src = "systolic_array.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "systolic_array.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "systolic_array.v:6.17-6.19" *)
  input [7:0] a1;
  wire [7:0] a1;
  (* src = "systolic_array.v:6.21-6.23" *)
  input [7:0] a2;
  wire [7:0] a2;
  (* src = "systolic_array.v:7.17-7.19" *)
  input [7:0] b1;
  wire [7:0] b1;
  (* src = "systolic_array.v:7.21-7.23" *)
  input [7:0] b2;
  wire [7:0] b2;
  (* src = "systolic_array.v:8.19-8.22" *)
  output [15:0] c11;
  wire [15:0] c11;
  (* src = "systolic_array.v:8.24-8.27" *)
  output [15:0] c12;
  wire [15:0] c12;
  (* src = "systolic_array.v:8.29-8.32" *)
  output [15:0] c21;
  wire [15:0] c21;
  (* src = "systolic_array.v:8.34-8.37" *)
  output [15:0] c22;
  wire [15:0] c22;
  (* src = "systolic_array.v:11.16-11.25" *)
  wire [7:0] a11_to_12;
  (* src = "systolic_array.v:11.27-11.36" *)
  wire [7:0] a21_to_22;
  (* src = "systolic_array.v:12.16-12.25" *)
  wire [7:0] b11_to_21;
  (* src = "systolic_array.v:12.27-12.36" *)
  wire [7:0] b12_to_22;
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array.v:15.8-20.6" *)
  pe pe11 (
    .a_in(a1),
    .a_out(a11_to_12),
    .b_in(b1),
    .b_out(b11_to_21),
    .c(c11),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array.v:23.8-28.6" *)
  pe pe12 (
    .a_in(a11_to_12),
    .b_in(b2),
    .b_out(b12_to_22),
    .c(c12),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array.v:31.8-36.6" *)
  pe pe21 (
    .a_in(a2),
    .a_out(a21_to_22),
    .b_in(b11_to_21),
    .c(c21),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array.v:39.8-44.6" *)
  pe pe22 (
    .a_in(a21_to_22),
    .b_in(b12_to_22),
    .c(c22),
    .clk(clk),
    .rst(rst)
  );
endmodule
