/* Generated by Yosys 0.58+86 (git sha1 3b9f06c13, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

(* src = "pe_4x4.v:1.1-15.10" *)
module pe(clk, rst, a_in, b_in, c);
  (* src = "pe_4x4.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "pe_4x4.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "pe_4x4.v:4.17-4.21" *)
  input [7:0] a_in;
  wire [7:0] a_in;
  (* src = "pe_4x4.v:5.17-5.21" *)
  input [7:0] b_in;
  wire [7:0] b_in;
  (* src = "pe_4x4.v:6.23-6.24" *)
  output [31:0] c;
  reg [31:0] c;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.20-198.21" *)
  wire [31:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [31:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [31:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [31:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [31:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [31:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [31:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.20-198.21" *)
  wire [31:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [31:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [31:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [31:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [31:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [31:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [31:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [31:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [31:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [31:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [31:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.23-198.24" *)
  wire [31:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:198.26-198.27" *)
  wire [31:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [31:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [31:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [31:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [31:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [31:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [31:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [31:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [31:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  wire [31:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.19-203.21" *)
  wire [31:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.23-203.25" *)
  wire [31:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:203.27-203.29" *)
  wire [31:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "31" *)
  wire [31:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _043_;
  (* force_downto = 32'd1 *)
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _044_;
  (* force_downto = 32'd1 *)
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [31:0] _045_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _046_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _047_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _048_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _049_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _050_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _051_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _052_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _053_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _054_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _055_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _056_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _057_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _058_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _059_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _060_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _061_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _062_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _063_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _064_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _065_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _066_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _067_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _068_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _069_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _070_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _071_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _072_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _073_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _074_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _075_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _076_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _077_;
  (* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _078_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _079_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _080_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _081_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _082_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _083_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _084_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _085_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _086_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _087_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _088_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _089_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _090_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _091_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _092_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _093_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _094_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _095_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _096_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _097_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _098_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _099_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _100_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _101_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _102_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _103_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _104_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _105_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _106_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _107_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _108_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _109_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _110_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _111_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _112_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _113_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _114_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _115_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _116_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _117_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _118_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _119_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _120_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _121_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _122_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _123_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _124_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _125_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _126_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _127_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _128_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _129_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _130_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _131_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _132_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _133_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _134_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _135_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _136_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _137_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _138_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _139_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _140_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _141_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _142_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _143_;
  (* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _144_;
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[14] <= 1'h0;
    else c[14] <= _044_[14];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[15] <= 1'h0;
    else c[15] <= _044_[15];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[16] <= 1'h0;
    else c[16] <= _044_[16];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[17] <= 1'h0;
    else c[17] <= _044_[17];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[18] <= 1'h0;
    else c[18] <= _044_[18];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[19] <= 1'h0;
    else c[19] <= _044_[19];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[20] <= 1'h0;
    else c[20] <= _044_[20];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[21] <= 1'h0;
    else c[21] <= _044_[21];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[22] <= 1'h0;
    else c[22] <= _044_[22];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[23] <= 1'h0;
    else c[23] <= _044_[23];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[24] <= 1'h0;
    else c[24] <= _044_[24];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[25] <= 1'h0;
    else c[25] <= _044_[25];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[26] <= 1'h0;
    else c[26] <= _044_[26];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[27] <= 1'h0;
    else c[27] <= _044_[27];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[28] <= 1'h0;
    else c[28] <= _044_[28];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[29] <= 1'h0;
    else c[29] <= _044_[29];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[30] <= 1'h0;
    else c[30] <= _044_[30];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[31] <= 1'h0;
    else c[31] <= _044_[31];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[0] <= 1'h0;
    else c[0] <= _043_[0];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[1] <= 1'h0;
    else c[1] <= _044_[1];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[2] <= 1'h0;
    else c[2] <= _044_[2];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[3] <= 1'h0;
    else c[3] <= _044_[3];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[4] <= 1'h0;
    else c[4] <= _044_[4];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[5] <= 1'h0;
    else c[5] <= _044_[5];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[6] <= 1'h0;
    else c[6] <= _044_[6];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[7] <= 1'h0;
    else c[7] <= _044_[7];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[8] <= 1'h0;
    else c[8] <= _044_[8];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[9] <= 1'h0;
    else c[9] <= _044_[9];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[10] <= 1'h0;
    else c[10] <= _044_[10];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[11] <= 1'h0;
    else c[11] <= _044_[11];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[12] <= 1'h0;
    else c[12] <= _044_[12];
  (* src = "pe_4x4.v:8.5-14.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c[13] <= 1'h0;
    else c[13] <= _044_[13];
  assign _016_[3] = _019_[3] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[3];
  assign _016_[4] = _019_[4] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[4];
  assign _016_[5] = _019_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[5];
  assign _016_[6] = _019_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[6];
  assign _016_[7] = _019_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[7];
  assign _016_[8] = _019_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[8];
  assign _016_[9] = _019_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _020_[9];
  assign _017_[3] = _018_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _008_[3];
  assign _017_[4] = _018_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[4];
  assign _017_[5] = _018_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[5];
  assign _017_[6] = _018_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[6];
  assign _017_[7] = _018_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[7];
  assign _017_[8] = _018_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[8];
  assign _017_[9] = _018_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _012_[9];
  assign _020_[3] = _008_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[3];
  assign _020_[4] = _012_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[4];
  assign _020_[5] = _012_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[5];
  assign _020_[6] = _012_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[6];
  assign _020_[7] = _012_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[7];
  assign _020_[8] = _012_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[8];
  assign _020_[9] = _012_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _018_[9];
  assign _016_[2] = _004_[2] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[1];
  assign _019_[3] = _004_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[2];
  assign _019_[4] = _004_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[3];
  assign _019_[5] = _004_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[4];
  assign _019_[6] = _004_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[5];
  assign _019_[7] = _004_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[6];
  assign _019_[8] = _004_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[7];
  assign _019_[9] = _002_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _003_[8];
  assign _017_[2] = _004_[2] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[1];
  assign _018_[3] = _004_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[2];
  assign _018_[4] = _004_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[3];
  assign _018_[5] = _004_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[4];
  assign _018_[6] = _004_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[5];
  assign _018_[7] = _004_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[6];
  assign _018_[8] = _004_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[7];
  assign _018_[9] = _002_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _003_[8];
  assign _023_[7] = _026_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[7];
  assign _023_[8] = _026_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[8];
  assign _023_[9] = _026_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[9];
  assign _023_[10] = _026_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[10];
  assign _023_[11] = _026_[11] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[11];
  assign _023_[12] = _026_[12] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _027_[12];
  assign _024_[7] = _025_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[7];
  assign _024_[8] = _025_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[8];
  assign _024_[9] = _025_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[9];
  assign _024_[10] = _025_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[10];
  assign _024_[11] = _025_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[11];
  assign _024_[12] = _025_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[12];
  assign _024_[13] = _021_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _022_[13];
  assign _027_[7] = _022_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[7];
  assign _027_[8] = _022_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[8];
  assign _027_[9] = _022_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[9];
  assign _027_[10] = _022_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[10];
  assign _027_[11] = _022_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[11];
  assign _027_[12] = _022_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _025_[12];
  assign _023_[13] = _022_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _021_[13];
  assign _023_[6] = _011_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[6];
  assign _026_[7] = _011_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[7];
  assign _026_[8] = _011_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[8];
  assign _026_[9] = _011_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[9];
  assign _026_[10] = _011_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[10];
  assign _026_[11] = _011_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[11];
  assign _026_[12] = _011_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _021_[12];
  assign _024_[6] = _011_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[6];
  assign _025_[7] = _011_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[7];
  assign _025_[8] = _011_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[8];
  assign _025_[9] = _011_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[9];
  assign _025_[10] = _011_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[10];
  assign _025_[11] = _011_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[11];
  assign _025_[12] = _011_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _021_[12];
  assign _028_[5] = _031_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[5];
  assign _028_[6] = _031_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[6];
  assign _028_[7] = _031_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[7];
  assign _028_[8] = _031_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[8];
  assign _028_[9] = _031_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[9];
  assign _028_[10] = _031_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _032_[10];
  assign _029_[5] = _030_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _011_[4];
  assign _029_[6] = _030_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[6];
  assign _029_[7] = _030_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[7];
  assign _029_[8] = _030_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[8];
  assign _029_[9] = _030_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[9];
  assign _029_[10] = _030_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[10];
  assign _029_[11] = _012_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[11];
  assign _029_[12] = _010_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _024_[12];
  assign _032_[5] = _011_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[5];
  assign _032_[6] = _024_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[6];
  assign _032_[7] = _024_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[7];
  assign _032_[8] = _024_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[8];
  assign _032_[9] = _024_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[9];
  assign _032_[10] = _024_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _030_[10];
  assign _028_[11] = _024_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _012_[11];
  assign _028_[12] = _024_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _010_[12];
  assign _028_[3] = _017_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[2];
  assign _028_[4] = _017_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[3];
  assign _031_[5] = _017_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[4];
  assign _031_[6] = _017_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[5];
  assign _031_[7] = _017_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[6];
  assign _031_[8] = _017_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[7];
  assign _031_[9] = _017_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[8];
  assign _031_[10] = _012_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _016_[9];
  assign _029_[3] = _017_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[2];
  assign _029_[4] = _017_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[3];
  assign _030_[5] = _017_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[4];
  assign _030_[6] = _017_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[5];
  assign _030_[7] = _017_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[6];
  assign _030_[8] = _017_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[7];
  assign _030_[9] = _017_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[8];
  assign _030_[10] = _012_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _016_[9];
  assign _033_[7] = _036_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[7];
  assign _033_[8] = _036_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[8];
  assign _033_[9] = _036_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[9];
  assign _033_[10] = _036_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[10];
  assign _033_[11] = _036_[11] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[11];
  assign _033_[12] = _036_[12] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[12];
  assign _033_[13] = _036_[13] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _037_[13];
  assign _034_[7] = _035_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[6];
  assign _034_[8] = _035_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[7];
  assign _034_[9] = _035_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[8];
  assign _034_[10] = _035_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[9];
  assign _034_[11] = _035_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[10];
  assign _034_[12] = _035_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[11];
  assign _034_[13] = _035_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[12];
  assign _034_[14] = _022_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _023_[13];
  assign _037_[7] = _023_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[7];
  assign _037_[8] = _023_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[8];
  assign _037_[9] = _023_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[9];
  assign _037_[10] = _023_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[10];
  assign _037_[11] = _023_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[11];
  assign _037_[12] = _023_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[12];
  assign _037_[13] = _023_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _035_[13];
  assign _033_[14] = _023_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _022_[14];
  assign _000_[0] = a_in[0] & b_in[0];
  assign _033_[4] = _029_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[3];
  assign _033_[5] = _029_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[4];
  assign _033_[6] = _029_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[5];
  assign _036_[7] = _029_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[6];
  assign _036_[8] = _029_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[7];
  assign _036_[9] = _029_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[8];
  assign _036_[10] = _029_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[9];
  assign _036_[11] = _029_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[10];
  assign _036_[12] = _029_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[11];
  assign _000_[1] = a_in[1] & b_in[0];
  assign _036_[13] = _024_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _028_[12];
  assign _000_[2] = a_in[2] & b_in[0];
  assign _000_[3] = a_in[3] & b_in[0];
  assign _034_[4] = _029_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[3];
  assign _034_[5] = _029_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[4];
  assign _034_[6] = _029_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[5];
  assign _035_[7] = _029_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[6];
  assign _035_[8] = _029_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[7];
  assign _035_[9] = _029_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[8];
  assign _035_[10] = _029_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[9];
  assign _000_[4] = a_in[4] & b_in[0];
  assign _035_[11] = _029_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[10];
  assign _035_[12] = _029_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[11];
  assign _035_[13] = _024_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _028_[12];
  assign _000_[5] = a_in[5] & b_in[0];
  assign _000_[6] = a_in[6] & b_in[0];
  assign _040_[6] = _039_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[5];
  assign _040_[7] = _039_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[6];
  assign _040_[8] = _039_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[7];
  assign _000_[7] = a_in[7] & b_in[0];
  assign _040_[9] = _039_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[8];
  assign _040_[10] = _039_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[9];
  assign _040_[11] = _039_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[10];
  assign _040_[12] = _039_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[11];
  assign _040_[13] = _039_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[12];
  assign _040_[14] = _039_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[13];
  assign _040_[15] = _033_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _038_[14];
  assign _042_[0] = _000_[0] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[0];
  assign _045_[1] = _004_[1] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[1];
  assign _045_[2] = _017_[2] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[2];
  assign _045_[3] = _029_[3] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[3];
  assign _045_[4] = _034_[4] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[4];
  assign _045_[5] = _039_[5] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[5];
  assign _045_[6] = _040_[6] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[6];
  assign _045_[7] = _040_[7] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[7];
  assign _045_[8] = _040_[8] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[8];
  assign _045_[9] = _040_[9] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[9];
  assign _045_[10] = _040_[10] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[10];
  assign _045_[11] = _040_[11] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[11];
  assign _045_[12] = _040_[12] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[12];
  assign _045_[13] = _040_[13] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[13];
  assign _045_[14] = _040_[14] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[14];
  assign _045_[15] = _040_[15] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[15];
  assign _045_[16] = _038_[15] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  c[16];
  assign _043_[0] = _000_[0] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[0];
  assign _043_[1] = _004_[1] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[1];
  assign _043_[2] = _017_[2] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[2];
  assign _043_[3] = _029_[3] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[3];
  assign _043_[4] = _034_[4] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[4];
  assign _043_[5] = _039_[5] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[5];
  assign _043_[6] = _040_[6] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[6];
  assign _043_[7] = _040_[7] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[7];
  assign _043_[8] = _040_[8] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[8];
  assign _043_[9] = _040_[9] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[9];
  assign _043_[10] = _040_[10] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[10];
  assign _043_[11] = _040_[11] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[11];
  assign _043_[12] = _040_[12] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[12];
  assign _043_[13] = _040_[13] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[13];
  assign _043_[14] = _040_[14] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[14];
  assign _043_[15] = _040_[15] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[15];
  assign _043_[16] = _038_[15] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  c[16];
  assign _079_ = _043_[1] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _042_[0];
  assign _080_ = _043_[3] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[2];
  assign _081_ = _043_[5] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[4];
  assign _082_ = _043_[7] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[6];
  assign _083_ = _043_[9] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[8];
  assign _084_ = _043_[11] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[10];
  assign _085_ = _043_[13] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[12];
  assign _086_ = _043_[15] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[14];
  assign _087_ = c[17] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _045_[16];
  assign _001_[1] = a_in[0] & b_in[1];
  assign _088_ = _097_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _042_[1];
  assign _089_ = _099_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _135_;
  assign _090_ = _101_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _137_;
  assign _091_ = _103_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _139_;
  assign _092_ = _105_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _087_;
  assign _001_[2] = a_in[1] & b_in[1];
  assign _093_ = _111_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _042_[3];
  assign _094_ = _113_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _142_;
  assign _095_ = _115_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _092_;
  assign _096_ = _117_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _042_[7];
  assign _001_[3] = a_in[2] & b_in[1];
  assign _097_ = _043_[3] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[2];
  assign _098_ = _043_[5] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[4];
  assign _099_ = _043_[7] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[6];
  assign _100_ = _043_[9] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[8];
  assign _101_ = _043_[11] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[10];
  assign _102_ = _043_[13] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[12];
  assign _103_ = _043_[15] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[14];
  assign _104_ = c[17] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _043_[16];
  assign _105_ = c[19] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  c[18];
  assign _106_ = c[21] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  c[20];
  assign _001_[4] = a_in[3] & b_in[1];
  assign _107_ = c[23] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  c[22];
  assign _108_ = c[25] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  c[24];
  assign _109_ = c[27] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  c[26];
  assign _110_ = c[29] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  c[28];
  assign _111_ = _099_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _098_;
  assign _112_ = _101_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _100_;
  assign _113_ = _103_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _102_;
  assign _114_ = _105_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _104_;
  assign _115_ = _107_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _106_;
  assign _001_[5] = a_in[4] & b_in[1];
  assign _116_ = _109_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _108_;
  assign _117_ = _113_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _112_;
  assign _118_ = _115_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _114_;
  assign _119_ = _118_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[15];
  assign _120_ = _112_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[7];
  assign _121_ = _114_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[15];
  assign _042_[27] = _116_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[23];
  assign _001_[6] = a_in[5] & b_in[1];
  assign _122_ = _098_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[3];
  assign _123_ = _100_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[7];
  assign _124_ = _102_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[11];
  assign _125_ = _104_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[15];
  assign _042_[21] = _106_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[19];
  assign _042_[25] = _108_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[23];
  assign _042_[29] = _110_ &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[27];
  assign _126_ = _043_[2] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[1];
  assign _127_ = _043_[4] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[3];
  assign _128_ = _043_[6] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[5];
  assign _001_[7] = a_in[6] & b_in[1];
  assign _129_ = _043_[8] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[7];
  assign _130_ = _043_[10] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[9];
  assign _131_ = _043_[12] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[11];
  assign _132_ = _043_[14] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[13];
  assign _133_ = _043_[16] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[15];
  assign _042_[18] = c[18] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[17];
  assign _042_[20] = c[20] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[19];
  assign _042_[22] = c[22] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[21];
  assign _042_[24] = c[24] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[23];
  assign _042_[26] = c[26] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[25];
  assign _001_[8] = a_in[7] & b_in[1];
  assign _042_[28] = c[28] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[27];
  assign _042_[30] = c[30] &(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _042_[29];
  assign _042_[1] = _045_[1] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _079_;
  assign _134_ = _045_[3] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _080_;
  assign _135_ = _045_[5] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _081_;
  assign _136_ = _045_[7] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _082_;
  assign _137_ = _045_[9] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _083_;
  assign _138_ = _045_[11] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _084_;
  assign _139_ = _045_[13] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _085_;
  assign _140_ = _045_[15] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _086_;
  assign _042_[3] = _134_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _088_;
  assign _141_ = _136_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _089_;
  assign _142_ = _138_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _090_;
  assign _143_ = _140_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _091_;
  assign _042_[7] = _141_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _093_;
  assign _144_ = _143_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _094_;
  assign _042_[15] = _144_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _096_;
  assign _042_[23] = _095_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _119_;
  assign _042_[11] = _142_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _120_;
  assign _042_[19] = _092_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _121_;
  assign _042_[5] = _135_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _122_;
  assign _042_[9] = _137_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _123_;
  assign _042_[13] = _139_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _124_;
  assign _042_[17] = _087_ |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _125_;
  assign _042_[2] = _045_[2] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _126_;
  assign _042_[4] = _045_[4] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _127_;
  assign _042_[6] = _045_[6] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _128_;
  assign _042_[8] = _045_[8] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _129_;
  assign _042_[10] = _045_[10] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _130_;
  assign _042_[12] = _045_[12] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _131_;
  assign _042_[14] = _045_[14] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _132_;
  assign _042_[16] = _045_[16] |(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _133_;
  assign _038_[5] = _034_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[4];
  assign _041_[6] = _034_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[5];
  assign _041_[7] = _034_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[6];
  assign _041_[8] = _034_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[7];
  assign _041_[9] = _034_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[8];
  assign _041_[10] = _034_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[9];
  assign _041_[11] = _034_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[10];
  assign _041_[12] = _034_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[11];
  assign _041_[13] = _034_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[12];
  assign _041_[14] = _034_[14] &(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _033_[13];
  assign _039_[5] = _034_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[4];
  assign _039_[6] = _034_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[5];
  assign _039_[7] = _034_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[6];
  assign _039_[8] = _034_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[7];
  assign _039_[9] = _034_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[8];
  assign _039_[10] = _034_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[9];
  assign _039_[11] = _034_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[10];
  assign _039_[12] = _034_[12] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[11];
  assign _039_[13] = _034_[13] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[12];
  assign _039_[14] = _034_[14] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _033_[13];
  assign _046_ = _039_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[6];
  assign _047_ = _039_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[8];
  assign _048_ = _039_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[10];
  assign _049_ = _039_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[12];
  assign _050_ = _033_[14] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _041_[14];
  assign _051_ = _056_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _038_[5];
  assign _052_ = _058_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _073_;
  assign _053_ = _060_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _075_;
  assign _054_ = _062_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _076_;
  assign _055_ = _063_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _038_[7];
  assign _056_ = _039_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[6];
  assign _057_ = _039_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[8];
  assign _058_ = _039_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[10];
  assign _059_ = _039_[13] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[12];
  assign _060_ = _033_[14] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _039_[14];
  assign _002_[2] = a_in[0] & b_in[2];
  assign _061_ = _058_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _057_;
  assign _062_ = _060_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _059_;
  assign _002_[3] = a_in[1] & b_in[2];
  assign _063_ = _062_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _061_;
  assign _064_ = _061_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _002_[4] = a_in[2] & b_in[2];
  assign _065_ = _057_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _066_ = _059_ &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _002_[5] = a_in[3] & b_in[2];
  assign _067_ = _039_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[5];
  assign _068_ = _039_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _069_ = _039_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[9];
  assign _070_ = _039_[12] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _071_ = _039_[14] &(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _038_[13];
  assign _002_[6] = a_in[4] & b_in[2];
  assign _072_ = _041_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _046_;
  assign _073_ = _041_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _047_;
  assign _002_[7] = a_in[5] & b_in[2];
  assign _074_ = _041_[11] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _048_;
  assign _075_ = _041_[13] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _049_;
  assign _002_[8] = a_in[6] & b_in[2];
  assign _038_[7] = _072_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _051_;
  assign _076_ = _074_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _052_;
  assign _077_ = _050_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _053_;
  assign _002_[9] = a_in[7] & b_in[2];
  assign _078_ = _077_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _054_;
  assign _038_[15] = _078_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _055_;
  assign _038_[11] = _076_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _064_;
  assign _038_[9] = _073_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _065_;
  assign _038_[13] = _075_ |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _066_;
  assign _038_[6] = _041_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _067_;
  assign _038_[8] = _041_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _068_;
  assign _038_[10] = _041_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _069_;
  assign _038_[12] = _041_[12] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _070_;
  assign _038_[14] = _041_[14] |(* src = "/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _071_;
  assign _008_[3] = a_in[0] & b_in[3];
  assign _008_[4] = a_in[1] & b_in[3];
  assign _008_[5] = a_in[2] & b_in[3];
  assign _008_[6] = a_in[3] & b_in[3];
  assign _008_[7] = a_in[4] & b_in[3];
  assign _008_[8] = a_in[5] & b_in[3];
  assign _008_[9] = a_in[6] & b_in[3];
  assign _008_[10] = a_in[7] & b_in[3];
  assign _009_[4] = a_in[0] & b_in[4];
  assign _009_[5] = a_in[1] & b_in[4];
  assign _009_[6] = a_in[2] & b_in[4];
  assign _009_[7] = a_in[3] & b_in[4];
  assign _009_[8] = a_in[4] & b_in[4];
  assign _009_[9] = a_in[5] & b_in[4];
  assign _009_[10] = a_in[6] & b_in[4];
  assign _009_[11] = a_in[7] & b_in[4];
  assign _010_[5] = a_in[0] & b_in[5];
  assign _010_[6] = a_in[1] & b_in[5];
  assign _010_[7] = a_in[2] & b_in[5];
  assign _010_[8] = a_in[3] & b_in[5];
  assign _010_[9] = a_in[4] & b_in[5];
  assign _010_[10] = a_in[5] & b_in[5];
  assign _010_[11] = a_in[6] & b_in[5];
  assign _010_[12] = a_in[7] & b_in[5];
  assign _021_[6] = a_in[0] & b_in[6];
  assign _021_[7] = a_in[1] & b_in[6];
  assign _021_[8] = a_in[2] & b_in[6];
  assign _021_[9] = a_in[3] & b_in[6];
  assign _021_[10] = a_in[4] & b_in[6];
  assign _021_[11] = a_in[5] & b_in[6];
  assign _021_[12] = a_in[6] & b_in[6];
  assign _021_[13] = a_in[7] & b_in[6];
  assign _022_[7] = a_in[0] & b_in[7];
  assign _022_[8] = a_in[1] & b_in[7];
  assign _022_[9] = a_in[2] & b_in[7];
  assign _022_[10] = a_in[3] & b_in[7];
  assign _022_[11] = a_in[4] & b_in[7];
  assign _022_[12] = a_in[5] & b_in[7];
  assign _022_[13] = a_in[6] & b_in[7];
  assign _022_[14] = a_in[7] & b_in[7];
  assign _044_[1] = _043_[1] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[0];
  assign _044_[2] = _043_[2] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[1];
  assign _044_[3] = _043_[3] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[2];
  assign _044_[4] = _043_[4] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[3];
  assign _044_[5] = _043_[5] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[4];
  assign _044_[6] = _043_[6] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[5];
  assign _044_[7] = _043_[7] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[6];
  assign _044_[8] = _043_[8] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[7];
  assign _044_[9] = _043_[9] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[8];
  assign _044_[10] = _043_[10] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[9];
  assign _044_[11] = _043_[11] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[10];
  assign _044_[12] = _043_[12] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[11];
  assign _044_[13] = _043_[13] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[12];
  assign _044_[14] = _043_[14] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[13];
  assign _044_[15] = _043_[15] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[14];
  assign _044_[16] = _043_[16] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[15];
  assign _044_[17] = c[17] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[16];
  assign _044_[18] = c[18] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[17];
  assign _044_[19] = c[19] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[18];
  assign _044_[20] = c[20] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[19];
  assign _044_[21] = c[21] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[20];
  assign _044_[22] = c[22] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[21];
  assign _044_[23] = c[23] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[22];
  assign _044_[24] = c[24] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[23];
  assign _044_[25] = c[25] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[24];
  assign _044_[26] = c[26] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[25];
  assign _044_[27] = c[27] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[26];
  assign _044_[28] = c[28] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[27];
  assign _044_[29] = c[29] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[28];
  assign _044_[30] = c[30] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[29];
  assign _044_[31] = c[31] ^(* src = "pe_4x4.v:12.18-12.33|/usr/local/bin/../share/yosys/techmap.v:296.13-296.25" *)  _042_[30];
  assign _003_[2] = _006_[2] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[2];
  assign _003_[3] = _006_[3] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[3];
  assign _003_[4] = _006_[4] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[4];
  assign _003_[5] = _006_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[5];
  assign _003_[6] = _006_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[6];
  assign _003_[7] = _006_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _007_[7];
  assign _004_[2] = _005_[2] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[2];
  assign _004_[3] = _005_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[3];
  assign _004_[4] = _005_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[4];
  assign _004_[5] = _005_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[5];
  assign _004_[6] = _005_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[6];
  assign _004_[7] = _005_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[7];
  assign _004_[8] = _001_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _002_[8];
  assign _007_[2] = _002_[2] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[2];
  assign _007_[3] = _002_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[3];
  assign _007_[4] = _002_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[4];
  assign _007_[5] = _002_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[5];
  assign _007_[6] = _002_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[6];
  assign _007_[7] = _002_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _005_[7];
  assign _003_[8] = _002_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _001_[8];
  assign _003_[1] = _000_[1] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[1];
  assign _006_[2] = _000_[2] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[2];
  assign _006_[3] = _000_[3] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[3];
  assign _006_[4] = _000_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[4];
  assign _006_[5] = _000_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[5];
  assign _006_[6] = _000_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[6];
  assign _006_[7] = _000_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _001_[7];
  assign _004_[1] = _000_[1] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[1];
  assign _005_[2] = _000_[2] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[2];
  assign _005_[3] = _000_[3] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[3];
  assign _005_[4] = _000_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[4];
  assign _005_[5] = _000_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[5];
  assign _005_[6] = _000_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[6];
  assign _005_[7] = _000_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _001_[7];
  assign _011_[5] = _014_[5] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[5];
  assign _011_[6] = _014_[6] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[6];
  assign _011_[7] = _014_[7] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[7];
  assign _011_[8] = _014_[8] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[8];
  assign _011_[9] = _014_[9] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[9];
  assign _011_[10] = _014_[10] |(* src = "/usr/local/bin/../share/yosys/techmap.v:206.25-206.32" *)  _015_[10];
  assign _012_[5] = _013_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[5];
  assign _012_[6] = _013_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[6];
  assign _012_[7] = _013_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[7];
  assign _012_[8] = _013_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[8];
  assign _012_[9] = _013_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[9];
  assign _012_[10] = _013_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[10];
  assign _012_[11] = _009_[11] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:206.13-206.19" *)  _010_[11];
  assign _015_[5] = _010_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[5];
  assign _015_[6] = _010_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[6];
  assign _015_[7] = _010_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[7];
  assign _015_[8] = _010_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[8];
  assign _015_[9] = _010_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[9];
  assign _015_[10] = _010_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _013_[10];
  assign _011_[11] = _010_[11] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.38-205.44" *)  _009_[11];
  assign _011_[4] = _008_[4] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[4];
  assign _014_[5] = _008_[5] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[5];
  assign _014_[6] = _008_[6] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[6];
  assign _014_[7] = _008_[7] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[7];
  assign _014_[8] = _008_[8] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[8];
  assign _014_[9] = _008_[9] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[9];
  assign _014_[10] = _008_[10] &(* src = "/usr/local/bin/../share/yosys/techmap.v:205.26-205.31" *)  _009_[10];
  assign _012_[4] = _008_[4] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[4];
  assign _013_[5] = _008_[5] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[5];
  assign _013_[6] = _008_[6] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[6];
  assign _013_[7] = _008_[7] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[7];
  assign _013_[8] = _008_[8] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[8];
  assign _013_[9] = _008_[9] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[9];
  assign _013_[10] = _008_[10] ^(* src = "/usr/local/bin/../share/yosys/techmap.v:205.14-205.19" *)  _009_[10];
  assign _000_[31:8] = 24'h000000;
  assign { _001_[31:9], _001_[0] } = 24'h000000;
  assign { _002_[31:10], _002_[1:0] } = 24'h000000;
  assign { _003_[31:9], _003_[0] } = 24'h000000;
  assign { _004_[31:9], _004_[0] } = { 22'h000000, _002_[9], _000_[0] };
  assign { _005_[31:8], _005_[1:0] } = { 23'h000000, _001_[8], _004_[1], _000_[0] };
  assign { _006_[31:8], _006_[1:0] } = { 24'h000000, _003_[1], 1'h0 };
  assign { _007_[31:8], _007_[1:0] } = { 23'h000000, _003_[8], 2'h0 };
  assign { _008_[31:11], _008_[2:0] } = 24'h000000;
  assign { _009_[31:12], _009_[3:0] } = 24'h000000;
  assign { _010_[31:13], _010_[4:0] } = 24'h000000;
  assign { _011_[31:12], _011_[3:0] } = 24'h000000;
  assign { _012_[31:12], _012_[3:0] } = { 19'h00000, _010_[12], _008_[3], 3'h0 };
  assign { _013_[31:11], _013_[4:0] } = { 20'h00000, _009_[11], _012_[4], _008_[3], 3'h0 };
  assign { _014_[31:11], _014_[4:0] } = { 21'h000000, _011_[4], 4'h0 };
  assign { _015_[31:11], _015_[4:0] } = { 20'h00000, _011_[11], 5'h00 };
  assign { _016_[31:10], _016_[1:0] } = 24'h000000;
  assign { _017_[31:10], _017_[1:0] } = { 19'h00000, _010_[12], _012_[11:10], _004_[1], _000_[0] };
  assign { _018_[31:10], _018_[2:0] } = { 22'h000000, _017_[2], _004_[1], _000_[0] };
  assign { _019_[31:10], _019_[2:0] } = { 22'h000000, _016_[2], 2'h0 };
  assign { _020_[31:10], _020_[2:0] } = 25'h0000000;
  assign { _021_[31:14], _021_[5:0] } = 24'h000000;
  assign { _022_[31:15], _022_[6:0] } = 24'h000000;
  assign { _023_[31:14], _023_[5:0] } = 24'h000000;
  assign { _024_[31:14], _024_[5:0] } = { 17'h00000, _022_[14], _011_[4], 5'h00 };
  assign { _025_[31:13], _025_[6:0] } = { 18'h00000, _021_[13], _024_[6], _011_[4], 5'h00 };
  assign { _026_[31:13], _026_[6:0] } = { 19'h00000, _023_[6], 6'h00 };
  assign { _027_[31:13], _027_[6:0] } = { 18'h00000, _023_[13], 7'h00 };
  assign { _028_[31:13], _028_[2:0] } = 22'h000000;
  assign { _029_[31:13], _029_[2:0] } = { 17'h00000, _022_[14], _024_[13], _017_[2], _004_[1], _000_[0] };
  assign { _030_[31:11], _030_[4:0] } = { 19'h00000, _010_[12], _012_[11], _029_[4:3], _017_[2], _004_[1], _000_[0] };
  assign { _031_[31:11], _031_[4:0] } = { 21'h000000, _028_[4:3], 3'h0 };
  assign { _032_[31:11], _032_[4:0] } = { 19'h00000, _028_[12:11], 5'h00 };
  assign { _033_[31:15], _033_[3:0] } = 21'h000000;
  assign { _034_[31:15], _034_[3:0] } = { 17'h00000, _029_[3], _017_[2], _004_[1], _000_[0] };
  assign { _035_[31:14], _035_[6:0] } = { 17'h00000, _022_[14], _034_[6:4], _029_[3], _017_[2], _004_[1], _000_[0] };
  assign { _036_[31:14], _036_[6:0] } = { 18'h00000, _033_[6:4], 4'h0 };
  assign { _037_[31:14], _037_[6:0] } = { 17'h00000, _033_[14], 7'h00 };
  assign { _038_[31:16], _038_[4:0] } = 21'h000000;
  assign { _039_[31:15], _039_[4:0] } = { 16'h0000, _033_[14], _034_[4], _029_[3], _017_[2], _004_[1], _000_[0] };
  assign { _040_[31:16], _040_[5:0] } = { 15'h0000, _038_[15], _039_[5], _034_[4], _029_[3], _017_[2], _004_[1], _000_[0] };
  assign { _041_[31:15], _041_[5:0] } = { 17'h00000, _038_[5], 5'h00 };
  assign _043_[31:17] = c[31:17];
  assign _044_[0] = _043_[0];
  assign { _045_[31:17], _045_[0] } = { 15'h0000, _042_[0] };
endmodule

(* top =  1  *)
(* src = "systolic_array_4x4.v:1.1-66.10" *)
module systolic_array_4x4(clk, rst, a1, a2, a3, a4, b1, b2, b3, b4, c11, c12, c13, c14, c21, c22, c23, c24, c31, c32, c33
, c34, c41, c42, c43, c44);
  (* src = "systolic_array_4x4.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "systolic_array_4x4.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "systolic_array_4x4.v:4.17-4.19" *)
  input [7:0] a1;
  wire [7:0] a1;
  (* src = "systolic_array_4x4.v:4.21-4.23" *)
  input [7:0] a2;
  wire [7:0] a2;
  (* src = "systolic_array_4x4.v:4.25-4.27" *)
  input [7:0] a3;
  wire [7:0] a3;
  (* src = "systolic_array_4x4.v:4.29-4.31" *)
  input [7:0] a4;
  wire [7:0] a4;
  (* src = "systolic_array_4x4.v:5.17-5.19" *)
  input [7:0] b1;
  wire [7:0] b1;
  (* src = "systolic_array_4x4.v:5.21-5.23" *)
  input [7:0] b2;
  wire [7:0] b2;
  (* src = "systolic_array_4x4.v:5.25-5.27" *)
  input [7:0] b3;
  wire [7:0] b3;
  (* src = "systolic_array_4x4.v:5.29-5.31" *)
  input [7:0] b4;
  wire [7:0] b4;
  (* src = "systolic_array_4x4.v:6.19-6.22" *)
  output [31:0] c11;
  wire [31:0] c11;
  (* src = "systolic_array_4x4.v:6.24-6.27" *)
  output [31:0] c12;
  wire [31:0] c12;
  (* src = "systolic_array_4x4.v:6.29-6.32" *)
  output [31:0] c13;
  wire [31:0] c13;
  (* src = "systolic_array_4x4.v:6.34-6.37" *)
  output [31:0] c14;
  wire [31:0] c14;
  (* src = "systolic_array_4x4.v:7.19-7.22" *)
  output [31:0] c21;
  wire [31:0] c21;
  (* src = "systolic_array_4x4.v:7.24-7.27" *)
  output [31:0] c22;
  wire [31:0] c22;
  (* src = "systolic_array_4x4.v:7.29-7.32" *)
  output [31:0] c23;
  wire [31:0] c23;
  (* src = "systolic_array_4x4.v:7.34-7.37" *)
  output [31:0] c24;
  wire [31:0] c24;
  (* src = "systolic_array_4x4.v:8.19-8.22" *)
  output [31:0] c31;
  wire [31:0] c31;
  (* src = "systolic_array_4x4.v:8.24-8.27" *)
  output [31:0] c32;
  wire [31:0] c32;
  (* src = "systolic_array_4x4.v:8.29-8.32" *)
  output [31:0] c33;
  wire [31:0] c33;
  (* src = "systolic_array_4x4.v:8.34-8.37" *)
  output [31:0] c34;
  wire [31:0] c34;
  (* src = "systolic_array_4x4.v:9.19-9.22" *)
  output [31:0] c41;
  wire [31:0] c41;
  (* src = "systolic_array_4x4.v:9.24-9.27" *)
  output [31:0] c42;
  wire [31:0] c42;
  (* src = "systolic_array_4x4.v:9.29-9.32" *)
  output [31:0] c43;
  wire [31:0] c43;
  (* src = "systolic_array_4x4.v:9.34-9.37" *)
  output [31:0] c44;
  wire [31:0] c44;
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:12.8-13.39" *)
  pe PE11 (
    .a_in(a1),
    .b_in(b1),
    .c(c11),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:15.8-16.39" *)
  pe PE12 (
    .a_in(a1),
    .b_in(b2),
    .c(c12),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:18.8-19.39" *)
  pe PE13 (
    .a_in(a1),
    .b_in(b3),
    .c(c13),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:21.8-22.39" *)
  pe PE14 (
    .a_in(a1),
    .b_in(b4),
    .c(c14),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:26.8-27.39" *)
  pe PE21 (
    .a_in(a2),
    .b_in(b1),
    .c(c21),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:29.8-30.39" *)
  pe PE22 (
    .a_in(a2),
    .b_in(b2),
    .c(c22),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:32.8-33.39" *)
  pe PE23 (
    .a_in(a2),
    .b_in(b3),
    .c(c23),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:35.8-36.39" *)
  pe PE24 (
    .a_in(a2),
    .b_in(b4),
    .c(c24),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:40.8-41.39" *)
  pe PE31 (
    .a_in(a3),
    .b_in(b1),
    .c(c31),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:43.8-44.39" *)
  pe PE32 (
    .a_in(a3),
    .b_in(b2),
    .c(c32),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:46.8-47.39" *)
  pe PE33 (
    .a_in(a3),
    .b_in(b3),
    .c(c33),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:49.8-50.39" *)
  pe PE34 (
    .a_in(a3),
    .b_in(b4),
    .c(c34),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:54.8-55.39" *)
  pe PE41 (
    .a_in(a4),
    .b_in(b1),
    .c(c41),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:57.8-58.39" *)
  pe PE42 (
    .a_in(a4),
    .b_in(b2),
    .c(c42),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:60.8-61.39" *)
  pe PE43 (
    .a_in(a4),
    .b_in(b3),
    .c(c43),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "systolic_array_4x4.v:63.8-64.39" *)
  pe PE44 (
    .a_in(a4),
    .b_in(b4),
    .c(c44),
    .clk(clk),
    .rst(rst)
  );
endmodule
